=== Niki1os1/EpamJavaCourseTask3/src/main/resources/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <element name="plants">
    <complexType>
      <sequence>
        <element name="plant" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="name" type="string" />
              <element name="soil">
                <simpleType>
                  <restriction base="string">
                    <enumeration value="PODZOLIC"/>
                    <enumeration value="UNPAVED"/>
                    <enumeration value="SOD-PODZOLIC"/>
                  </restriction>
                </simpleType>
              </element>
              <element name="origin" type="string"/>
              <element name="visualParameters">
                <complexType>
                  <sequence>
                    <element name="stemColor" type="string" />
                    <element name="leafPresence" type="boolean" />
                    <element name="averagePlantSize">
                      <simpleType>
                        <restriction base="double">
                          <minInclusive value="0.1"/>
                        </restriction>
                      </simpleType>
                    </element>
                  </sequence>
                </complexType>
              </element>
              <element name="growingTips">
                <complexType>
                  <sequence>
                    <element name="temperature">
                      <simpleType>
                        <restriction base="double">
                          <minInclusive value="-20"/>
                          <maxInclusive value="40"/>
                        </restriction>
                      </simpleType>
                    </element>
                    <element name="lighting" type="boolean" />
                    <element name="watering" type="positiveInteger" />
                  </sequence>
                </complexType>
              </element>
              <element name="multiplying">
                <simpleType>
                  <restriction base="string">
                    <enumeration value="STALKS"/>
                    <enumeration value="SEEDS"/>
                    <enumeration value="LEAVES"/>
                  </restriction>
                </simpleType>
              </element>
            </sequence>
            <attribute name="id" type="string" use="required" />
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== Niki1os1/EpamJavaCourseTask3/src/main/resources/greenhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="greenhouse.xsd">
    <plant id="pl#1">
        <name>Rose</name>
        <soil>PODZOLIC</soil>
        <origin>Persia</origin>
        <visualParameters>
            <stemColor>green</stemColor>
            <leafPresence>true</leafPresence>
            <averagePlantSize>15</averagePlantSize>
        </visualParameters>
        <growingTips>
            <temperature>21</temperature>
            <lighting>true</lighting>
            <watering>10000</watering>
        </growingTips>
        <multiplying>STALKS</multiplying>
    </plant>
    <plant id="pl#2">
        <name>Chamomile</name>
        <soil>UNPAVED</soil>
        <origin>Eurasia</origin>
        <visualParameters>
            <stemColor>green</stemColor>
            <leafPresence>true</leafPresence>
            <averagePlantSize>10</averagePlantSize>
        </visualParameters>
        <growingTips>
            <temperature>18</temperature>
            <lighting>true</lighting>
            <watering>4000</watering>
        </growingTips>
        <multiplying>SEEDS</multiplying>
    </plant>
</plants>
